version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:dubnium
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          TEST_DATABASE: test
          NODE_ENV: test
          JWT_SECRET: secret
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run ci:test
  build-and-deploy:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: npm install --production
      - run: scp -r node_modules flashcards@callumcancreate.com:~/flash_cards
      - run: scp -r dist flashcards@callumcancreate.com:~/flash_cards/dist
      - run: ssh flashcards@callumcancreate.com "sudo systemctl restart flashcards"
workflows:
  build-and-test:
    jobs:
      - test
      - build-and-deploy:
          filters:
            branches:
              only: circle-deploy
          requires:
            - test
